/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelGLTF({model, ...props}) {
  useGLTF.preload(model)

  const group = useRef()
  const { nodes, materials } = useGLTF(model)

  let _material = materials['Material.001']
  _material.wireframe = false

  const MeshName = Object.keys(nodes)

  console.log(MeshName)

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes[MeshName[1]].geometry}
        onPointerOver={ console.log('in') }
        onPointerLeave={ console.log('out') }
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <meshStandardMaterial attach="material" color={0xffffff} />
      </mesh>
    </group>
  )
}

