/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BCube1(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1/BCube1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
      receiveShadow
      castShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.003']}
        position={[118.64, 3.03, -55.4]}
        scale={6.64}
      />
    </group>
  )
}

useGLTF.preload('/1/BCube1.gltf')
