/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BDoorFrame(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1/BDoorFrame.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh receiveShadow castShadow geometry={nodes.DoorFrame1010.geometry} material={materials['Material.004']} />
        <mesh receiveShadow castShadow geometry={nodes.DoorFrame1010_1.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/1/BDoorFrame.glb')
