/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BDoorBlock(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1/BDoorBlock.glb')

  const materialProps = {
    roughness: { value: 1, min: 0, max: 1, step: 0.1 },
    clearcoat: { value: 1, min: 0, max: 1, step: 0.1 },
    clearcoatRoughness: { value: 0, min: 0, max: 1, step: 0.1 },
    transmission: { value: 1, min: 0.9, max: 1, step: 0.01 },
    ior: { value: 1.25, min: 1, max: 2.3, step: 0.05 },
    envMapIntensity: { value: 25, min: 0, max: 100, step: 1 },
    color: '#ffffff'
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[114.49, 20.49, -37.58]} scale={0.23}>
        <mesh receiveShadow castShadow geometry={nodes.Circle_1.geometry} material={materials['Material.005']} />
        <mesh receiveShadow castShadow geometry={nodes.Circle_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle_3.geometry}>
          <meshStandardMaterial attach="material" color={'#413C3E'} transparent opacity={0.7}/>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/1/BDoorBlock.glb')

/*

*/
