/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber' 

const BMan = React.forwardRef((props, ref) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1/BMan.gltf')

  let ManMaterial = materials['Material.011']
  ManMaterial.transparent = true
  ManMaterial.emissive = {r: 255, g: 255, b: 255}
  ManMaterial.emissiveIntensity = (0).toFixed(0)



  useFrame(() => {
    if(ref.current) {
    group.current.rotation.y = ref.current.rotation.y
    }
  })

  return (
    <group position={[67.32, 8.73, 10]} ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={ManMaterial}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[4.58, 5.16, 8.66]}
      />
    </group>
  )
})

BMan.displayName = "BMan"

useGLTF.preload('/1/BMan.gltf')

export default BMan
