/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BPlatform(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1/BPlatform.gltf')

  const StandardMaterial = (<meshStandardMaterial color="grey"/>)


  return (
    <group ref={group} {...props} dispose={null}>
      <mesh receiveShadow castShadow
        geometry={nodes.platform.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        material={materials['Material.010']}>
      </mesh>
      <mesh receiveShadow castShadow
        geometry={nodes.platform.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        position
        scale={0.01}>
          <shadowMaterial attach="material" transparent opacity={.5} />
      </mesh>
        
    </group>
  )
}

useGLTF.preload('/1/BPlatform.gltf')

//material={materials['Material.010']}
//<shadowMaterial attachArray="material" transparent opacity={0.4} />
