/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const BRoof = React.forwardRef((props, ref) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1/BRoof.gltf')
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh receiveShadow castShadow geometry={nodes.Roof_1.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Roof_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
})

BRoof.displayName = "BRoof"

useGLTF.preload('/1/BRoof.gltf')

export default BRoof
