/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BWalls(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1/BWalls.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh receiveShadow castShadow geometry={nodes.walls001_1.geometry} material={materials['Material.001']} />
        <mesh receiveShadow castShadow geometry={nodes.walls001_2.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.walls001_3.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/1/BWalls.gltf')
